import random

# Word bank categorized by type and starting letter
# can be combined into 1 external file when all functions are done, which can be used by all functions
# words in this word bank is generated by ChatGPT, as it is not part of actual code
word_bank = { 
    'a': {
        'nouns': ["apple", "astronaut", "ant"],
        'adjectives': ["amazing", "angry", "awesome"],
        'verbs': ["arrive", "ask", "admire"],
        'adverbs': ["anxiously", "angrily", "awkwardly"]
    },
    'b': {
        'nouns': ["banana", "butterfly", "box"],
        'adjectives': ["beautiful", "brave", "bold"],
        'verbs': ["bounce", "build", "break"],
        'adverbs': ["briskly", "boldly", "brightly"]
    },
    'c': {
        'nouns': ["cat", "castle", "carrot"],
        'adjectives': ["charming", "colorful", "curious"],
        'verbs': ["climb", "catch", "create"],
        'adverbs': ["carefully", "cheerfully", "cleverly"]
    },
    'd': {
        'nouns': ["dog", "dolphin", "dragon"],
        'adjectives': ["delightful", "daring", "dynamic"],
        'verbs': ["dance", "dive", "discover"],
        'adverbs': ["diligently", "deeply", "dramatically"]
    },
    'e': {
        'nouns': ["elephant", "engine", "earth"],
        'adjectives': ["eager", "elegant", "energetic"],
        'verbs': ["explore", "enjoy", "examine"],
        'adverbs': ["easily", "excitedly", "enthusiastically"]
    },
    'f': {
        'nouns': ["fish", "flower", "forest"],
        'adjectives': ["fantastic", "fearless", "friendly"],
        'verbs': ["fly", "float", "follow"],
        'adverbs': ["freely", "fiercely", "fast"]
    },
    'g': {
        'nouns': ["giraffe", "garden", "game"],
        'adjectives': ["graceful", "generous", "great"],
        'verbs': ["gallop", "glide", "gather"],
        'adverbs': ["gently", "gladly", "gracefully"]
    },
    'h': {
        'nouns': ["horse", "house", "hamburger"],
        'adjectives': ["happy", "helpful", "honest"],
        'verbs': ["hop", "hug", "hide"],
        'adverbs': ["happily", "honestly", "hurriedly"]
    },
    'i': {
        'nouns': ["ice", "island", "idea"],
        'adjectives': ["interesting", "intelligent", "imaginative"],
        'verbs': ["improve", "invent", "inspire"],
        'adverbs': ["instantly", "innocently", "intensely"]
    },
    'j': {
        'nouns': ["jellyfish", "jungle", "jacket"],
        'adjectives': ["jolly", "joyful", "jazzy"],
        'verbs': ["jump", "jog", "juggle"],
        'adverbs': ["joyfully", "jokingly", "justly"]
    },
    'k': {
        'nouns': ["kangaroo", "kite", "kitchen"],
        'adjectives': ["kind", "keen", "knowledgeable"],
        'verbs': ["kick", "kneel", "knit"],
        'adverbs': ["keenly", "kindly", "knowingly"]
    },
    'l': {
        'nouns': ["lion", "lake", "leaf"],
        'adjectives': ["lively", "lucky", "lovely"],
        'verbs': ["leap", "laugh", "listen"],
        'adverbs': ["loudly", "lightly", "lovingly"]
    },
    'm': {
        'nouns': ["monkey", "mountain", "mirror"],
        'adjectives': ["magnificent", "mighty", "mysterious"],
        'verbs': ["move", "munch", "measure"],
        'adverbs': ["madly", "magically", "merrily"]
    },
    'n': {
        'nouns': ["night", "nest", "necklace"],
        'adjectives': ["noble", "nice", "noisy"],
        'verbs': ["nod", "notice", "navigate"],
        'adverbs': ["neatly", "nicely", "nervously"]
    },
    'o': {
        'nouns': ["octopus", "ocean", "orange"],
        'adjectives': ["outstanding", "optimistic", "original"],
        'verbs': ["observe", "offer", "open"],
        'adverbs': ["obediently", "oddly", "openly"]
    },
    'p': {
        'nouns': ["penguin", "piano", "planet"],
        'adjectives': ["peaceful", "powerful", "playful"],
        'verbs': ["paint", "push", "plan"],
        'adverbs': ["politely", "patiently", "perfectly"]
    },
    'q': {
        'nouns': ["queen", "quilt", "quokka"],
        'adjectives': ["quick", "quiet", "quirky"],
        'verbs': ["quack", "question", "quiver"],
        'adverbs': ["quickly", "quietly", "quizzically"]
    },
    'r': {
        'nouns': ["rabbit", "rainbow", "river"],
        'adjectives': ["radiant", "robust", "remarkable"],
        'verbs': ["run", "roar", "rest"],
        'adverbs': ["rapidly", "randomly", "rightfully"]
    },
    's': {
        'nouns': ["sun", "star", "snake"],
        'adjectives': ["shiny", "smart", "spectacular"],
        'verbs': ["shine", "slide", "sing"],
        'adverbs': ["softly", "smoothly", "swiftly"]
    },
    't': {
        'nouns': ["tiger", "tree", "table"],
        'adjectives': ["tall", "tough", "terrific"],
        'verbs': ["talk", "tickle", "throw"],
        'adverbs': ["tenderly", "thoroughly", "thoughtfully"]
    },
    'u': {
        'nouns': ["umbrella", "unicorn", "universe"],
        'adjectives': ["unique", "useful", "unbelievable"],
        'verbs': ["understand", "unfold", "upgrade"],
        'adverbs': ["unexpectedly", "urgently", "utterly"]
    },
    'v': {
        'nouns': ["violet", "village", "vase"],
        'adjectives': ["vibrant", "vast", "victorious"],
        'verbs': ["vanish", "visit", "vote"],
        'adverbs': ["visibly", "vividly", "valiantly"]
    },
    'w': {
        'nouns': ["whale", "window", "wagon"],
        'adjectives': ["wonderful", "wise", "warm"],
        'verbs': ["wave", "whisper", "wander"],
        'adverbs': ["wildly", "warmly", "wisely"]
    },
    'x': {
        'nouns': ["xylophone", "xerox", "x-ray"],
        'adjectives': ["xenophobic", "xeric", "xenial"],
        'verbs': ["x-ray", "xerox", "xenograft"],
        'adverbs': ["xenophobically", "xerically", "xenially"]
    },
    'y': {
        'nouns': ["yak", "yogurt", "yacht"],
        'adjectives': ["yellow", "yummy", "young"],
        'verbs': ["yell", "yawn", "yank"],
        'adverbs': ["yearly", "youthfully", "yawningly"]
    },
    'z': {
        'nouns': ["zebra", "zoo", "zipper"],
        'adjectives': ["zesty", "zealous", "zigzagging"],
        'verbs': ["zoom", "zap", "zigzag"],
        'adverbs': ["zestfully", "zealously", "zigzaggingly"]
    }
}

def generate_sentence(start_letter: str) -> str:
    """
    Generates a sentence where all words start with the given letter.

    Parameters:
        start_letter (str): The letter that all words in the sentence should start with.

    Returns:
        str: A generated sentence following a random sentence structure.

    Raises:
        ValueError: If the given letter is not available in the word bank.

    Example:
        >>> generate_sentence('b')
        'Beautiful banana bounces briskly.'
    """

    sentence_structures = [
        "{adjective} {noun} {verb} {adverb}.",
        "{adjective} {noun} {verb} {adjective} {noun} {adverb}.",
        "{noun} {verb} {adverb} {adjective} {noun}.",
        "{adjective} {noun} {adverb} {verb} {adjective} {noun}.",
        "{noun} {adverb} {verb} {adjective} {noun}."
    ]

    key = start_letter.lower()

    if key not in word_bank:
        raise ValueError(f"You provided an unsupported letter '{start_letter}'. Available letters are: {list(word_bank.keys())}")

    noun = random.choice(word_bank[key]['nouns'])
    adjective = random.choice(word_bank[key]['adjectives'])
    verb = random.choice(word_bank[key]['verbs'])
    adverb = random.choice(word_bank[key]['adverbs'])

    sentence_template = random.choice(sentence_structures)
    sentence = sentence_template.format(noun=noun, adjective=adjective, verb=verb, adverb=adverb)

    return sentence.capitalize()
